name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Dep install
        run: sudo apt-get -y update && sudo apt-get -y install rustc cargo
      - name: Test
        run: cargo test
